---
title: "Symphonic experiment Storyboard"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---
### Introduction
In the world of classical music, there is a tendency to endlessly re-listen famous classical composers such as Mozart, Bach, Beethoven etc. These composers deserve to have their admirable reputation, however, this has as result that nearly 95 percent of all classical music played in concert halls are old works. 
What does this say about our corpus?
In the next visualization, we show the correlation (Pearson's R) between the popularity of a certain track, and the popularity of the accessory composer. This way it becomes visible how inclined people are to listen to symphonies from famous composers rather than from unknown composers.

### Composer vs track

```{r}
library(spotifyr)
library(ggplot2)
library(tidyverse)
library("ggpubr")
sym <- readRDS("sym.rds")
artists <- sym %>%
  select(track.album.artists)
i = 1
while (i < length(artists$track.album.artists))
{
  id <- artists[[1]][[i]]$id[[1]]
  f <- get_artist(id)
  if (i == 1) {
    table = c(f$name,f$type,f$uri,f$followers$total, f$popularity, id, sym$track.popularity[[i]])
  }
  table <- rbind(table, c(f$name,f$type,f$uri,f$followers$total, f$popularity, id, sym$track.popularity[[i]]))
  i = i + 1
}               
table <- table %>% as.data.frame(row.names = 1:nrow(.))
colnames(table) <- c('name', 'type', 'uri', 'followers', 'composer_popularity', 'id', 'track_popularity')
table$composer_popularity <- as.integer(table$composer_popularity)  
table$track_popularity <- as.integer(table$track_popularity)   
composer <- table %>%
  arrange(composer_popularity)
ggscatter(composer, x = "composer_popularity", y = "track_popularity", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab="composer popularity", ylab="track popularity")
```

------------------------------------------------------------------------

As is visible in the graph, the black line resembles a straight upwards trend. Which means there is a positive correlation between a composers popularity and the popularity of their symphonies. The total Pearson's R amounts to 0.59 (approximately).


------------------------------------------------------------------------
### Discussion
The former visualization shows us that people tend to be more interested in famous composer's symphonies, than those from unknown composers. 
From one perspective, this is expected because a composer's popularity is probably calculated from their tracks' popularity.
But from another perspective would it be somewhat prejudiced to listen to a composer's symphony purely based on their other works, disregarding the efforts of unknown composers.